NMBP/project3/portal/config/routes.rb
Rails.application.routes.draw do
	root 'posts#home'
	
	get	 'posts' => 'posts#new'
	post 'posts' => 'posts#create'
	
	post '/' => 'posts#comment'
	post 'comment' => 'posts#addComment'
	

end

NMBP/project3/portal/app/models/latest_post.rb
class LatestPost
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :postId, type: String
end

NMBP/project3/portal/app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :title, type: String
  field :content, type: String
  field :author, type: String
  field :image, type: String
  field :comments, type: Array
  
end

NMBP/project3/portal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

NMBP/project3/portal/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def home
		#@posts = Post.all
		
		# Get all cached posts
		@posts = Array.new
		sortedPOsts = LatestPost.order('created_at DESC').all # Sort
		sortedPOsts.each do |cache|
			if !cache.postId.nil?
				@posts << (Post.find(cache.postId))
			end
		end
	end
	
	def new
	end
	
	def create
		@post = Post.new(post_params)
		@post.save
		
		# Save the new post id in latestsPosts for fast retrieval
		latestId = LatestPost.new(postId:  Post.find_by(title: @post.title)[:id])
		
		# Check if the leatestPost documents are full (max 10)
		cachedNumberOfposts = 10
		if( LatestPost.count >= cachedNumberOfposts)
			# Remove the letest one and add the new one instead
			LatestPost.order('created_at ASC').limit(1).destroy
		end
		
		#Save the changes
		latestId.save
	
		redirect_to action: "home"
	end
	
	def comment
		@commentingPost = Post.find(params[:id])
	end
	
	def addComment
		@commentingPost = Post.find(params[:id])
		@commentingPost.add_to_set(comments: params[:comment])
		@commentingPost.save
	
		redirect_to action: "home"
	end
	
	private
		def post_params
		  params.require(:post).permit(:title, :image, :content, :author)
		end

end

NMBP/project3/portal/app/helpers/application_helper.rb
module ApplicationHelper
end

NMBP/project3/portal/app/helpers/posts_helper.rb
module PostsHelper
end

NMBP/project3/portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <%= link_to "PortalOut", root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
						<%= link_to "New post", posts_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
	

	<%= yield %>

</body>
</html>

NMBP/project3/portal/app/views/posts/comment.html.erb
<!-- Page Heading -->
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
        <small>Comment on the post <%= @commentingPost.title %> by the author <%= @commentingPost.author %></small>
        </h1>
    </div>
</div>


<div class="row">
	<div class="col-md-5">
	</div>
    <div class="col-md-5">
          <%= form_for :comment, :url => url_for(:controller => 'posts', :action => 'addComment') do |f| %>
			  <p>
				<%= f.label :comment %><br>
				<%= f.text_field :content %>
			  </p>
			  
			  <%= hidden_field_tag "id", @commentingPost.id %>
			 
			  <p>
				<%= f.submit 'Comment', :class => 'btn btn-primary'  %>
			  </p>
		  <% end %>
     </div>
</div>        
        

NMBP/project3/portal/app/views/posts/home.html.erb
	<!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">PortalOut
                    <small>a fresh look of the web</small>
                </h1>
            </div>
        </div>

<!-- Page Content -->
    <div class="container">
    
	<% if !@posts.nil? %>
	  <% @posts.each do |post| %>
		  <div class="row">
				<div class="col-md-4">
					<a href="#">
						<img class="img-responsive" src="<%= post.image %>" alt="">
					</a>
				</div>
				<div class="col-md-8">
				
					<h3><%= post.title %></h3>
					<h4><%= post.author %></h4>
					<p><%= post.content %></p>					
					
					
					<div class="page-header">
					</div> 				
					
					<% if !post.comments.nil? %> 
						<% post.comments.each do |c| %>
							<% if !c.nil? %> 
							
								<div class="comments-list">
									<div class="media">
										<div class="media-body">
                                
										<h4 class="media-heading user_name">Anonymous</h4>
											<%= c["content"] %>.
			
										</div>
									</div>
								</div>
							
								<br>
							<% end %>
						<% end %>
					<% end %>

					
					<%= button_to 'Comment', :controller => "posts", :action => "comment", :class => 'btn btn-primary',  :id => post.id %>
					
					<!--<%= form_for :comment do |f| %>
					
					  
					  <p>
						<%= f.label :comments %><br>
						<%= f.text_field :comment %>
					  </p>
					  
					  <p>
						<%= f.submit 'Comment', :class => 'btn btn-primary' %>
					  </p>
					<% end %>-->
					
				</div>
			</div>
			<!-- /.row -->
			   <hr>
	  <% end %>
	<% end %>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Powered by Monster</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

NMBP/project3/portal/app/views/posts/new.html.erb
<!-- Page Heading -->
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
        <small>create a new post</small>
        </h1>
    </div>
</div>

<div class="row">
	<div class="col-md-5">
	</div>
    <div class="col-md-5">
          <%= form_for :post do |f| %>
          <p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		  </p>
          
          <p>
			<%= f.label :author %><br>
			<%= f.text_field :author %>
		  </p>
		  
		  <p>
			<%= f.label :content %><br>
			<%= f.text_area :content %>
		  </p>
		 
          <p>
			<%= f.label :image %><br>
			<%= f.text_field :image %>
		  </p>
		 
		  <p>
			<%= f.submit 'Post', :class => 'btn btn-primary' %>
		  </p>
		  <% end %>
     </div>
</div>        
        